// <auto-generated />
using System;
using ApiTiendaZapas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTiendaZapas.Migrations
{
    [DbContext(typeof(ZapatillasContext))]
    partial class ZapatillasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTiendaZapas.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colores");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Id_variante")
                        .HasColumnType("int");

                    b.Property<int?>("Id_zapatilla")
                        .HasColumnType("int");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_variante");

                    b.HasIndex("Id_zapatilla");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Variante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Talla")
                        .HasColumnType("int");

                    b.Property<int>("ZapatillaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ZapatillaId");

                    b.ToTable("Variantes");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Zapatilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Zapatillas");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Imagen", b =>
                {
                    b.HasOne("ApiTiendaZapas.Models.Variante", "Variante")
                        .WithMany("Imagenes")
                        .HasForeignKey("Id_variante")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ApiTiendaZapas.Models.Zapatilla", "Zapatilla")
                        .WithMany("Imagenes")
                        .HasForeignKey("Id_zapatilla")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Variante");

                    b.Navigation("Zapatilla");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Variante", b =>
                {
                    b.HasOne("ApiTiendaZapas.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTiendaZapas.Models.Zapatilla", "Zapatilla")
                        .WithMany("Variantes")
                        .HasForeignKey("ZapatillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Zapatilla");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Zapatilla", b =>
                {
                    b.HasOne("ApiTiendaZapas.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Variante", b =>
                {
                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("ApiTiendaZapas.Models.Zapatilla", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Variantes");
                });
#pragma warning restore 612, 618
        }
    }
}
